/**
 * Generate this repository's wire types from the pinned core contract. Offline and deterministic:
 * the only input is `contracts/core-openapi.json`.
 *
 *   node scripts/generate-api.mjs           # write shared/generated/*     (npm run generate:api)
 *   node scripts/generate-api.mjs --check   # fail if they are stale       (npm run generate:check)
 *
 * Two outputs:
 *
 *  - `shared/generated/api.ts` — every route and model, by `openapi-typescript`.
 *  - `shared/generated/events.ts` — one tolerant valibot schema per member of the `TurnEvent` union,
 *    written in the vocabulary of `shared/eventCoercion.ts`. A field's helper follows from its
 *    schema (a string is `text`, an integer `count`, an enum `oneOf`, ...) and its fallback from the
 *    schema's `default`. Every field falls back rather than failing, so a malformed value costs that
 *    value and never the event; `shared/events.ts` holds the few readings that are a UI decision.
 *
 * A schema shape this file does not know throws, so a contract that grows a new shape cannot be
 * generated into something that quietly reads it wrong.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { argv, exit } from 'node:process';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { ROOT, readCopy, readLock, sha256 } from './lib/contractLock.mjs';

export const OUT_DIR = join(ROOT, 'shared', 'generated');

const banner = (lock, what) =>
  `/**\n` +
  ` * GENERATED by scripts/generate-api.mjs from contracts/core-openapi.json — do not edit.\n` +
  ` * ${what}\n` +
  ` * Contract ${lock.contract_version}, ${lock.repository}@${lock.commit}, sha256 ${lock.sha256.slice(0, 16)}….\n` +
  ` * Regenerate with \`npm run generate:api\`; \`npm run generate:check\` fails when this is stale.\n` +
  ` */\n\n`;

/* ── events ──────────────────────────────────────────────────────────────── */

const refName = (schema) => schema.$ref.split('/').pop();
const lowerFirst = (name) => name[0].toLowerCase() + name.slice(1);
/** A TypeScript literal in this repository's style (single quotes), for strings, numbers and lists. */
function literal(value) {
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(value)) return `[${value.map(literal).join(', ')}]`;
  return JSON.stringify(value);
}

/** `T | null` as `[T, true]`; any other schema as `[schema, false]`. */
function unwrapNullable(schema) {
  if (!Array.isArray(schema.anyOf)) return [schema, false];
  const rest = schema.anyOf.filter((member) => member.type !== 'null');
  if (rest.length === 1 && rest.length < schema.anyOf.length) return [rest[0], true];
  return [schema, false];
}

/**
 * The valibot expression for one property, and whether its fallback was a guess.
 *
 * A fallback is a guess when the schema states none and the field is a closed set: the first member
 * is not a reading of anything, so `shared/events.ts` must state one (a test holds that).
 */
function fieldExpression(where, schema, schemas) {
  const [inner, nullable] = unwrapNullable(schema);
  const fail = () => {
    throw new Error(
      `scripts/generate-api.mjs: ${where} has a schema shape it cannot generate: ${JSON.stringify(schema)}`,
    );
  };
  const stated = 'default' in schema;
  const fallback = schema.default;

  if (inner.enum) {
    if (inner.type !== 'string') fail();
    if (nullable) return { code: `oneOfOrNull(${literal(inner.enum)} as const)`, guessed: false };
    return {
      code: `oneOf(${literal(inner.enum)} as const, ${literal(stated ? fallback : inner.enum[0])})`,
      guessed: !stated,
    };
  }
  switch (inner.type) {
    case 'string':
      return {
        code: nullable ? 'textOrNull()' : `text(${stated ? literal(fallback) : ''})`,
        guessed: false,
      };
    case 'integer':
      return {
        code: nullable ? 'countOrNull()' : `count(${stated ? literal(fallback) : ''})`,
        guessed: false,
      };
    case 'number':
      return {
        code: nullable ? 'numberOrNull()' : `finiteNumber(${stated ? literal(fallback) : ''})`,
        guessed: false,
      };
    case 'boolean':
      if (nullable) fail();
      return { code: `flag(${stated ? literal(fallback) : ''})`, guessed: false };
    case 'object':
      if (nullable || inner.additionalProperties !== true) fail();
      return { code: 'anyObject()', guessed: false };
    case 'array': {
      if (nullable) fail();
      const items = inner.items ?? fail();
      if (items.type === 'string' && !items.enum) return { code: 'textList()', guessed: false };
      if (items.type === 'string' && items.enum)
        return { code: `listOf(${literal(items.enum)} as const)`, guessed: false };
      if (items.type === 'number' || items.type === 'integer')
        return { code: 'numberList()', guessed: false };
      if (items.$ref) {
        return {
          code: `rowsOf(${rowExpression(where, schemas[refName(items)])})`,
          guessed: false,
        };
      }
      return fail();
    }
    default:
      return fail();
  }
}

/** A strict row: a required property must be well-formed, or the row is dropped by `rowsOf`. */
function rowExpression(where, schema) {
  if (schema?.type !== 'object') throw new Error(`${where}: a row must be an object schema`);
  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties ?? {}).map(([name, property]) => {
    let base;
    if (property.type === 'string') base = 'v.string()';
    else if (property.type === 'number' || property.type === 'integer')
      base = 'v.pipe(v.number(), v.finite())';
    else if (property.type === 'boolean') base = 'v.boolean()';
    else throw new Error(`${where}.${name}: a row property must be a string, number or boolean`);
    const code = required.has(name)
      ? base
      : `v.optional(${base}, ${literal(property.default ?? '')})`;
    return `${name}: ${code}`;
  });
  return `v.object({ ${entries.join(', ')} })`;
}

function generateEvents(document, lock) {
  const schemas = document.components.schemas;
  const union = schemas.TurnEvent;
  if (!union?.oneOf || union.discriminator?.propertyName !== 'type')
    throw new Error('TurnEvent is not a oneOf with a discriminator on `type`');

  const members = union.oneOf.map((member) => {
    const name = refName(member);
    const schema = schemas[name];
    const kind = schema.properties?.type?.const;
    if (typeof kind !== 'string') throw new Error(`${name} has no \`type\` const`);
    return { name, schema, kind };
  });

  const guessed = [];
  const enums = {};
  const blocks = members.map(({ name, schema, kind }) => {
    const lines = [`  type: v.literal(${literal(kind)}),`];
    for (const [property, definition] of Object.entries(schema.properties)) {
      if (property === 'type') continue;
      const where = `${name}.${property}`;
      const { code, guessed: isGuess } = fieldExpression(where, definition, schemas);
      const [inner] = unwrapNullable(definition);
      const closed = inner.enum ?? inner.items?.enum ?? null;
      if (closed) enums[where] = closed;
      if (isGuess) guessed.push(where);
      lines.push(`  ${property}: ${code},`);
    }
    const variable = lowerFirst(name);
    return (
      `export const ${variable} = v.object({\n${lines.join('\n')}\n});\n` +
      `export type ${name} = v.InferOutput<typeof ${variable}>;\n`
    );
  });

  const header =
    banner(lock, 'Tolerant valibot schemas for the members of the `TurnEvent` union.') +
    `import * as v from 'valibot';\n` +
    `import {\n  anyObject,\n  count,\n  countOrNull,\n  finiteNumber,\n  flag,\n  listOf,\n  numberList,\n` +
    `  numberOrNull,\n  oneOf,\n  oneOfOrNull,\n  rowsOf,\n  text,\n  textList,\n  textOrNull,\n` +
    `} from '../eventCoercion.ts';\n\n`;

  const table =
    `\n/** Every member, by its wire discriminator, in the document's union order. */\n` +
    `export const EVENT_SCHEMAS = {\n` +
    members.map(({ name, kind }) => `  ${kind}: ${lowerFirst(name)},`).join('\n') +
    `\n} as const;\n\n` +
    `export type TurnEventKind = keyof typeof EVENT_SCHEMAS;\n\n` +
    `/** The document's model name for each wire discriminator. */\n` +
    `export const EVENT_MODELS = {\n` +
    members.map(({ name, kind }) => `  ${kind}: ${literal(name)},`).join('\n') +
    `\n} as const satisfies Record<TurnEventKind, string>;\n\n` +
    `/** The members of every closed set the events carry, as \`Model.field\`. */\n` +
    `export const EVENT_ENUMS = {\n` +
    Object.entries(enums)
      .map(([where, values]) => `  ${literal(where)}: ${literal(values)},`)
      .join('\n') +
    `\n} as const;\n\n` +
    `/**\n * Closed-set fields whose fallback is not stated by the document, so the generator took the\n` +
    ` * first member. \`shared/events.ts\` must state a reading for each (a test holds that).\n */\n` +
    `export const GUESSED_FALLBACKS: readonly string[] = ${literal(guessed)};\n`;

  return header + blocks.join('\n') + table;
}

/* ── driver ──────────────────────────────────────────────────────────────── */

/** The pinned contract: its lock, bytes and parsed document, refused if the copy was edited. */
export function loadPinned() {
  const lock = readLock();
  const { bytes, document } = readCopy();
  if (sha256(bytes) !== lock.sha256) {
    throw new Error(
      'contracts/core-openapi.json does not match contracts/core.lock; run `npm run contract:check`.',
    );
  }
  return { lock, document };
}

/**
 * Every output, as `{ path relative to the repository root: text }`. Takes the document so a test
 * can generate from one it has altered; by default it is the pinned copy.
 */
export async function generate({ lock, document } = loadPinned()) {
  const types = astToString(await openapiTS(structuredClone(document)));
  return {
    'shared/generated/api.ts':
      banner(lock, 'Every route and model of the API contract, by openapi-typescript.') + types,
    'shared/generated/events.ts': generateEvents(document, lock),
  };
}

async function main() {
  const check = argv.includes('--check');
  const outputs = await generate();
  const stale = [];
  for (const [relative, text] of Object.entries(outputs)) {
    const file = resolve(ROOT, relative);
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (check) {
      if (current !== text) stale.push(relative);
      continue;
    }
    if (current !== text) {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, text);
      console.log(`generate:api wrote ${relative}`);
    }
  }
  if (check) {
    if (stale.length > 0) {
      console.error(
        `generate:check FAILED — stale relative to contracts/core-openapi.json: ${stale.join(', ')}.\n` +
          '  Run `npm run generate:api` and commit the result.',
      );
      exit(1);
    }
    console.log('generate:check ok — shared/generated/ matches the pinned contract.');
  }
}

if (argv[1] && resolve(argv[1]) === fileURLToPath(import.meta.url)) await main();
